import {
  Tag,
  Briefcase,
  Building2,
  Palette,
  Users,
  GraduationCap,
  Stethoscope,
  Code2,
  Shield,
  ShoppingBag,
  PenTool,
  Rocket,
  Music2,
  Camera,
  HeartPulse,
  Dumbbell,
  Leaf,
  Cpu,
  BookOpen,
  Globe,
  Hammer,
  Sparkles,
  LayoutGrid,
  Cloud,
  Database,
  Cog,
  Factory,
  Film,
  Car,
  Truck,
  Coins,
  Utensils,
  Microscope,
  Gamepad2,
  Paintbrush,
  Binary,
  PersonStanding,
  Layers,
  Megaphone,
  Beaker,
  FlaskConical,
  Braces,
  Bug,
  Feather,
  Anchor,
  Lightbulb
} from "lucide-react";

export const categoryIconOptions = [
  { value: "Tag", label: "Default", icon: Tag },
  { value: "Briefcase", label: "Business", icon: Briefcase },
  { value: "Building2", label: "Corporate", icon: Building2 },
  { value: "Palette", label: "Design", icon: Palette },
  { value: "Users", label: "People", icon: Users },
  { value: "GraduationCap", label: "Education", icon: GraduationCap },
  { value: "Stethoscope", label: "Healthcare", icon: Stethoscope },
  { value: "Code2", label: "Development", icon: Code2 },
  { value: "Shield", label: "Security", icon: Shield },
  { value: "ShoppingBag", label: "Retail", icon: ShoppingBag },
  { value: "PenTool", label: "Creative", icon: PenTool },
  { value: "Rocket", label: "Startups", icon: Rocket },
  { value: "Music2", label: "Music", icon: Music2 },
  { value: "Camera", label: "Media", icon: Camera },
  { value: "HeartPulse", label: "Wellness", icon: HeartPulse },
  { value: "Dumbbell", label: "Fitness", icon: Dumbbell },
  { value: "Leaf", label: "Environment", icon: Leaf },
  { value: "Cpu", label: "Technology", icon: Cpu },
  { value: "BookOpen", label: "Content", icon: BookOpen },
  { value: "Globe", label: "Global", icon: Globe },
  { value: "Hammer", label: "Construction", icon: Hammer },
  { value: "Sparkles", label: "Lifestyle", icon: Sparkles },
  { value: "LayoutGrid", label: "General", icon: LayoutGrid },
  { value: "Cloud", label: "Cloud", icon: Cloud },
  { value: "Database", label: "Data", icon: Database },
  { value: "Cog", label: "Operations", icon: Cog },
  { value: "Factory", label: "Manufacturing", icon: Factory },
  { value: "Film", label: "Film & TV", icon: Film },
  { value: "Car", label: "Automotive", icon: Car },
  { value: "Truck", label: "Logistics", icon: Truck },
  { value: "Coins", label: "Finance", icon: Coins },
  { value: "Utensils", label: "Hospitality", icon: Utensils },
  { value: "Microscope", label: "Research", icon: Microscope },
  { value: "Gamepad2", label: "Gaming", icon: Gamepad2 },
  { value: "Paintbrush", label: "Art", icon: Paintbrush },
  { value: "Binary", label: "AI & ML", icon: Binary },
  { value: "PersonStanding", label: "Customer Service", icon: PersonStanding },
  { value: "Layers", label: "Product", icon: Layers },
  { value: "Megaphone", label: "Marketing", icon: Megaphone },
  { value: "Beaker", label: "Science", icon: Beaker },
  { value: "FlaskConical", label: "Chemistry", icon: FlaskConical },
  { value: "Braces", label: "Dental", icon: Braces },
  { value: "Bug", label: "QA & Testing", icon: Bug },
  { value: "Feather", label: "Writing", icon: Feather },
  { value: "Anchor", label: "Marine", icon: Anchor },
  { value: "Lightbulb", label: "Innovation", icon: Lightbulb }
];

const iconMap = categoryIconOptions.reduce((acc, option) => {
  acc[option.value] = option.icon;
  return acc;
}, {});

export const getCategoryIcon = (iconName) => iconMap[iconName] || Tag;
